### ISSUE TITLE
Un eclipse solar

### ISSUE THREAD

**Issue by DeLuca-Agustin** [pdepjm/2021-kata0-prensentacion-luckberonne#3]
El ballet cósmico ha empezado

**Comment by luckberonne** [comment]
![image](https://user-images.githubusercontent.com/48859730/114067136-dad4b980-9872-11eb-8c72-2131aa4a2718.png)
AJAJAJAJAJ

**Comment by asanzo** [comment]
JAJAJAJAJ son lo más sépanlo.
